site_name: Portafolio de Antonio Martínez
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true 
  palette:
      - scheme: default
        primary: black

  features:
    - content.code.copy
    - content.tooltips
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css

nav:
  - Home: index.md
  - Ejemplo: ejemplo.md
  #- Comandos Basicos: comandos.md
  #- git: gitcmds.md
  - microcontroladores: controladores.md
  - Proyecto rana: rana.md
  - Análisis sobre las cafeteras de cápsulas: analisis_cafeteras.md
  - Raspberry Pi Pico 2:
      -Contador Binario de 4 Bits : practicas/sumador.md
      -Barrido de LEDs : practicas/barrido.md
      -Ping Pongs: practicas/pong.md
      -Inputs : practicas/inputs.md
      -Secuencia controlada : practicas/secuencia.md
      -Temporizadores : 
        -control de LEDs: practicas/temporizadores/temporizadores.md
        -comparativas de código: practicas/temporizadores/comparativa.md
      -Control con PWM :
        -Canción con pym :  practicas/PWM/control_pwm.md
        -Control Motor con PWM : practicas/PWM/pwm_motor.md
        -Generador de señal con pwm : practicas/PWM/seno_pwm.md

      

      